# Generated by Django 4.1.4 on 2022-12-08 01:09

import a_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmedia',
            name='image',
            field=models.ImageField(upload_to=a_app.models.image_directory_path),
        ),
    ]
