# Generated by Django 4.1.4 on 2022-12-09 08:29

import a_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_app', '0003_testtag_testarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(max_length=100)),
                ('lng', models.FloatField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to=a_app.models.image_directory_path)),
            ],
        ),
    ]
